### ISSUE TITLE
Header parsing helper

### ISSUE THREAD

**Issue by mekras** [php-http/client-tools#5]
Parsing response headers is a common task for HTTP client. I have extracted this functionality to a [separate class](https://github.com/php-http/curl-client/blob/master/src/Tools/HeadersParser.php) which can be used by any client implementation. I can create PR to add it to client-tools if somebody think that this can be useful.

**Comment by sagikazarmark** [comment]
We already have some sort of HeaderParser in the helper repository. We haven't decided yet about this repository and where it's content should belong.

**Comment by mekras** [comment]
OK. I was confused be this repo description, thinking that all staff for client implementors located here.

**Comment by sagikazarmark** [comment]
Well, sometimes even myself is confused :smile: 

Helper will definitely be deprecated and stuff will be moved, probably here.

**Comment by dbu** [comment]
+1 for that. there is utils for libraries and other *users* of php-http
and client-tools should be for implementors of HTTPlug clients. is your
header parser the same as the one in helper? otherwise we can try to
merge them while we move it.

**Comment by mekras** [comment]
> is your header parser the same as the one in helper?

No it works different. It not only parse headers but also setup response objected with the parsed values.

**Comment by sagikazarmark** [comment]
So it is actually a bit more then just a plain parser, right? I guess it can be done with a single `withHeaders` call (if that method still exists in the standard, they had it once), right?

**Comment by mekras** [comment]
1. It can be used in conjunction with one from php-http/helper. So it can be transformed from "parser" to "setter" (I don't have appropriate name).
2. Currently `withHeaders` not exists in PSR-7.

**Comment by dbu** [comment]
do you want to do a pull request so we see how that would look?

**Comment by mekras** [comment]
I *can* do a pull request if you think it makes sense.

**Comment by dbu** [comment]
if its reusable, i think it makes sense. and we already have the socket
and the curl client, so we should be able to reuse.

**Comment by mekras** [comment]
OK. I'll do it in the next few days.

**Comment by mekras** [comment]
Where should I create PR, here or in "helper" repo?

**Comment by dbu** [comment]
i think here. @sagikazarmark is that correct? we are fading out helper and consolidate things in here? can we update the github description of helper to say its going away?

**Comment by sagikazarmark** [comment]
Correct, helper should be ditched. I think stuff in it is rather useful for client implementors, so we should migrate content here.
